name: diffusion-exp
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.11,<3.13
  - pip
  - pip:
      - jupyter
      - jupyterlab
      - ipython
      - ipykernel
      - bayesflow
      - jax
